# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48ffa48affd34d3f6d99f10ec92818b0c661c39f9f3082bbef983293184251f2fdbc01c27c7de77f8cdc924c9efdb37d9d3b894e68d9ebe77735f37e72b536ee

test:
  secret_key_base: 2b589467337d6a835276c3800fc5c1422b2427515761ca215bcd9692a1dc1dded8ce8a92f183c9b90435e50191010eca4b9d34788e7daaf2c115535b6ffbf046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
